In [1]:
import pandas as pd
import numpy as np
import us
#from geopy.geocoders import Nominatim
from sklearn.neighbors import NearestNeighbors

In [2]:
demographicData = pd.read_csv("Data/Demographics/ACSDP1Y2019.csv", skiprows=[0])
incomeData = pd.read_csv("Data/Income/ACSST1Y2019.csv", skiprows=[0])
urbanData = pd.read_csv("2010CensusUrbanRural.csv", skiprows=[0])


In [3]:
demographicData

id  Geographic Area Name  \
0   0400000US01               Alabama   
1   0400000US02                Alaska   
2   0400000US04               Arizona   
3   0400000US05              Arkansas   
4   0400000US06            California   
5   0400000US08              Colorado   
6   0400000US09           Connecticut   
7   0400000US10              Delaware   
8   0400000US11  District of Columbia   
9   0400000US12               Florida   
10  0400000US13               Georgia   
11  0400000US15                Hawaii   
12  0400000US16                 Idaho   
13  0400000US17              Illinois   
14  0400000US18               Indiana   
15  0400000US19                  Iowa   
16  0400000US20                Kansas   
17  0400000US21              Kentucky   
18  0400000US22             Louisiana   
19  0400000US23                 Maine   
20  0400000US24              Maryland   
21  0400000US25         Massachusetts   
22  0400000US26              Michigan   
23  0400000US27             Minnesota   
24  0400000US28           Mississippi   
25  0400000US29              Missouri   
26  0400000US30               Montana   
27  0400000US31              Nebraska   
28  0400000US32                Nevada   
29  0400000US33         New Hampshire   
30  0400000US34            New Jersey   
31  0400000US35            New Mexico   
32  0400000US36              New York   
33  0400000US37        North Carolina   
34  0400000US38          North Dakota   
35  0400000US39                  Ohio   
36  0400000US40              Oklahoma   
37  0400000US41                Oregon   
38  0400000US42          Pennsylvania   
39  0400000US44          Rhode Island   
40  0400000US45        South Carolina   
41  0400000US46          South Dakota   
42  0400000US47             Tennessee   
43  0400000US48                 Texas   
44  0400000US49                  Utah   
45  0400000US50               Vermont   
46  0400000US51              Virginia   
47  0400000US53            Washington   
48  0400000US54         West Virginia   
49  0400000US55             Wisconsin   
50  0400000US56               Wyoming   
51  0400000US72           Puerto Rico   

    Estimate!!SEX AND AGE!!Total population  \
0                                   4903185   
1                                    731545   
2                                   7278717   
3                                   3017804   
4                                  39512223   
5                                   5758736   
6                                   3565287   
7                                    973764   
8                                    705749   
9                                  21477737   
10                                 10617423   
11                                  1415872   
12                                  1787065   
13                                 12671821   
14                                  6732219   
15                                  3155070   
16                                  2913314   
17                                  4467673   
18                                  4648794   
19                                  1344212   
20                                  6045680   
21                                  6892503   
22                                  9986857   
23                                  5639632   
24                                  2976149   
25                                  6137428   
26                                  1068778   
27                                  1934408   
28                                  3080156   
29                                  1359711   
30                                  8882190   
31                                  2096829   
32                                 19453561   
33                                 10488084   
34                                   762062   
35                                 11689100   
36                                  3956971   
37                                  4217737   
38    

In [4]:
margins = [column for column in demographicData.columns if "Margin" in column]

In [5]:
demographicData = demographicData.drop(columns = margins)

In [6]:
#This took forever to run and the geographic positions of the states don't change enough for fresh data to
#matter,so I saved the lat/long data and loaded it separately
#geolocator = Nominatim(user_agent = "MDST-election-prediction")
#lat = {}
#long = {}
#for index, state in demographicData["Geographic Area Name"].iteritems():
#    loc = geolocator.geocode(state)
#    lat[state] = loc.latitude
#    long[state] = loc.longitude
#demographicData["Longitude"] = demographicData["Geographic Area Name"].map(long)
#demographicData["Latitude"] = demographicData["Geographic Area Name"].map(lat)

In [7]:
#latlongCols = ["Longitude", "Latitude"]

In [8]:
#latLongData = demographicData[latlongCols]
#latLongData.to_csv("latitudeAndLongitude.csv", index = False)

In [9]:
feat_columns = ["Estimate!!SEX AND AGE!!Total population!!Median age (years)",
                "Percent!!RACE!!Total population!!One race!!Black or African American",
               "Percent!!RACE!!Total population!!One race!!American Indian and Alaska Native",
               "Percent!!RACE!!Total population!!One race!!Asian",
               "Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)"]

In [10]:
demoFeatData = demographicData[feat_columns]
latLongData = pd.read_csv("latitudeAndLongitude.csv")
#demographicData.to_csv("cleanDemographicData_2019.csv", index = False)

In [11]:
educationData = pd.read_csv("Data/ACSST1Y2019.S1501_data_with_overlays_2020-10-22T140417.csv",skiprows=([0]))

In [12]:
margins = [column for column in educationData.columns if "Margin" in column]

In [13]:
educationData = educationData.drop(columns = margins)

In [14]:
edu_columns = ["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years","Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher","Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over","Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher","Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher"]

#edu_columns = ["Geographic Area Name", "id", "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT"]

edu_columns

['Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher",
 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over',
 "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher",
 "Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher"]

In [15]:
educationData = educationData[edu_columns]
educationData

Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years  \
0                                              457530                           
1                                               67738                           
2                                              694529                           
3                                              282336                           
4                                             3683287                           
5                                              527473                           
6                                              341435                           
7                                               82507                           
8                                               72703                           
9                                             1761280                           
10                                            1034172                           
11                                             119017                           
12                                             166713                           
13                                            1162448                           
14                                             662783                           
15                                             310236                           
16                                             294932                           
17                                             417406                           
18                                             423707                           
19                                             106707                           
20                                             529535                           
21                                             690150                           
22                                             949408                           
23                                             489751                           
24                                             298065                           
25                                             558571                           
26                                             100304                           
27                                             187542                           
28                                             252953                           
29                                             123941                           
30                                             752937                           
31                                             196991                           
32                                            1766731                           
33                                            1007035                           
34                                              80981                           
35                                            1064448                           
36                                             385498                           
37                                             366803                           
38                                            1141628                           
39                                             108834                           
40                                             473210                           
41                                              81361                           
42                                             624460                           
43                                            2826700                           
44                                             364058                           
45                                              64872                           
46                                             805157                           
47                                             661604                           
48                                 

In [16]:
educationData['total_with_college'] = educationData["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years!!Bachelor's degree or higher"] + educationData["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over!!Bachelor's degree or higher"]

In [17]:
educationData['total_pop'] = educationData["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 18 to 24 years"] + educationData["Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population 25 years and over"]

In [18]:
educationData['percent_with_degree'] = educationData['total_with_college'] / educationData['total_pop'] * 100

In [19]:
edu_feats = ["percent_with_degree", "Estimate!!Percent!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher"]

In [20]:
eduFeatData = educationData[edu_feats]

demoFeatData

In [21]:
demofeat_array = demoFeatData.to_numpy()
latLong_array = latLongData.to_numpy()

In [22]:
edufeat_array = eduFeatData.to_numpy()

In [23]:
#rural-urban split
urbanData = pd.read_csv("2010CensusUrbanRural.csv", skiprows = [0])
urbanData["percentRural"] = (urbanData["Total!!Rural"]/(urbanData["Total!!Rural"] + urbanData["Total!!Urban"])) * 100
urbanRural_array = urbanData["percentRural"].to_numpy()
urbanRural_array

array([40.9631829 , 33.98021207, 10.19017941, 43.83967588,  5.04738342,
       26.81374924, 41.61952653, 13.84783969, 12.00736857, 16.70334345,
        0.        ,  8.83696934, 24.9338204 ,  8.0726251 , 29.42187394,
       11.51212972, 27.55639361, 35.98067198, 25.80184205, 61.34017786,
       12.80357395,  8.02794416, 25.43276566, 26.72764038, 50.65461934,
       29.56382671, 44.1069723 , 26.86546488,  5.80451915, 39.69691675,
        5.32044631, 22.5729769 , 12.12707519, 33.91256636, 40.10148813,
       22.07609862, 33.75642535, 18.9683624 , 21.34318304,  9.26534843,
       33.67421461, 43.34827679, 33.60896172, 15.30099885,  9.41754089,
       61.10451449, 24.54598311, 15.95158925, 51.27830959, 29.84617863,
       35.24198671,  6.24117469])

In [24]:
#religion

In [25]:
#unemployment
unemploymentData = pd.read_csv("Data/State unemployment - Sheet1.csv")

unemploymentData = unemploymentData.sort_values(by = "State")
unemploymentData = unemploymentData["Unemployment Percentage"]

In [26]:
unemployment_array = unemploymentData.to_numpy()
unemployment_array

array([ 6.6,  7.2,  6.7,  7.3, 11. ,  6.4,  7.8,  8.2,  8.7,  7.6,  6.4,
       15.1,  6.1, 10.2,  6.2,  4.7,  5.9,  5.6,  8.1,  6.1,  7.2,  9.6,
        8.5,  6. ,  7.1,  4.9,  5.3,  3.5, 12.6,  6. ,  6.7,  9.4,  9.7,
        7.3,  4.4,  8.4,  5.3,  8. ,  8.1, 10.5,  5.1,  4.1,  6.3,  8.3,
        5. ,  4.2,  6.2,  7.8,  8.6,  5.4,  6.1])

In [27]:
feat_array = np.concatenate((demofeat_array[0:51],edufeat_array[0:51], latLong_array[0:51],unemployment_array[:,np.newaxis], urbanRural_array[0:51,np.newaxis]), axis = 1)

In [28]:
feat_array

array([[ 3.94000000e+01,  2.69000000e+01,  5.00000000e-01,
         1.30000000e+00,  4.50000000e+00,  2.41082327e+01,
         2.85000000e+01, -8.68295337e+01,  3.32588817e+01,
         6.60000000e+00,  4.09631829e+01],
       [ 3.50000000e+01,  3.10000000e+00,  1.58000000e+01,
         6.00000000e+00,  7.20000000e+00,  2.70531138e+01,
         3.57000000e+01, -1.49680909e+02,  6.44459613e+01,
         7.20000000e+00,  3.39802121e+01],
       [ 3.83000000e+01,  4.70000000e+00,  4.60000000e+00,
         3.30000000e+00,  3.17000000e+01,  2.77012216e+01,
         3.11000000e+01, -1.11763275e+02,  3.43953420e+01,
         6.70000000e+00,  1.01901794e+01],
       [ 3.88000000e+01,  1.55000000e+01,  6.00000000e-01,
         1.50000000e+00,  7.70000000e+00,  2.15988325e+01,
         2.43000000e+01, -9.24479108e+01,  3.52048883e+01,
         7.30000000e+00,  4.38396759e+01],
       [ 3.70000000e+01,  5.80000000e+00,  8.00000000e-01,
         1.48000000e+01,  3.94000000e+01,  3.21865479e+01,
  

In [30]:
nbrs = NearestNeighbors().fit(feat_array)

In [31]:
distances, indices = nbrs.kneighbors(feat_array)

In [32]:
indices

array([[ 0, 40, 42,  3, 24],
       [ 1, 37, 12, 26, 50],
       [ 2, 28, 43,  4, 44],
       [ 3, 17, 42,  0, 36],
       [ 4, 28,  2, 43, 31],
       [ 5, 16, 27, 23, 37],
       [ 6, 29, 33, 46, 38],
       [ 7, 38, 46, 20, 32],
       [ 8, 20, 46, 21, 32],
       [ 9, 13, 32,  7, 39],
       [10,  7, 20, 13, 32],
       [11,  4, 37, 28, 44],
       [12, 50, 37, 27, 16],
       [13, 32, 30, 47, 39],
       [14, 17, 22, 25, 49],
       [15, 35, 27, 49, 22],
       [16, 27, 23, 25, 49],
       [17, 14, 42, 25,  3],
       [18,  0, 40, 42, 33],
       [19, 45, 29, 48,  6],
       [20,  7, 46, 32, 10],
       [21, 30, 32, 39, 47],
       [22, 35, 14, 38, 49],
       [23, 49, 27, 16, 25],
       [24,  0,  3, 40, 18],
       [25, 49, 14, 42, 22],
       [26, 41, 34, 50, 27],
       [27, 16, 23, 49, 25],
       [28,  2,  4, 44, 43],
       [29,  6, 45, 49, 19],
       [30, 32, 21, 39, 13],
       [31, 43,  2,  4, 28],
       [32, 30, 39, 21, 47],
       [33, 40, 42, 46,  0],
       [34, 41

In [33]:
demographicData['Abbreviation'] = demographicData["Geographic Area Name"].map(us.states.mapping('name', 'abbr'))

In [34]:
for state in indices:
    print(demographicData.iloc[state[0]]['Geographic Area Name'] + ': ' + demographicData.iloc[state[1]]['Geographic Area Name']
         + ', ' + demographicData.iloc[state[2]]['Geographic Area Name'] + ', ' + demographicData.iloc[state[3]]['Geographic Area Name'] + ', ' 
          + demographicData.iloc[state[4]]['Geographic Area Name'])

Alabama: South Carolina, Tennessee, Arkansas, Mississippi
Alaska: Oregon, Idaho, Montana, Wyoming
Arizona: Nevada, Texas, California, Utah
Arkansas: Kentucky, Tennessee, Alabama, Oklahoma
California: Nevada, Arizona, Texas, New Mexico
Colorado: Kansas, Nebraska, Minnesota, Oregon
Connecticut: New Hampshire, North Carolina, Virginia, Pennsylvania
Delaware: Pennsylvania, Virginia, Maryland, New York
District of Columbia: Maryland, Virginia, Massachusetts, New York
Florida: Illinois, New York, Delaware, Rhode Island
Georgia: Delaware, Maryland, Illinois, New York
Hawaii: California, Oregon, Nevada, Utah
Idaho: Wyoming, Oregon, Nebraska, Kansas
Illinois: New York, New Jersey, Washington, Rhode Island
Indiana: Kentucky, Michigan, Missouri, Wisconsin
Iowa: Ohio, Nebraska, Wisconsin, Michigan
Kansas: Nebraska, Minnesota, Missouri, Wisconsin
Kentucky: Indiana, Tennessee, Missouri, Arkansas
Louisiana: Alabama, South Carolina, Tennessee, North Carolina
Maine: Vermont, New Hampshire, West Virgini